version: '3.9'
services:
  web:
    build: .
    ports:
      - "8050:8050"
    depends_on:
      db:
        condition: service_started
    env_file:
      - ./.env
    networks:
      - dash-network

  db:
    image: postgres:latest
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_PORT=${POSTGRES_PORT}
      - POSTGRES_DB=${POSTGRES_DB}
    env_file:
      - ./.env
    ports:
      - "5432:5432"
    networks:
      - dash-network

networks:
  dash-network:
    driver: bridge