"""Initial db

Revision ID: f4c4d7c12b3a
Revises: 
Create Date: 2022-11-04 15:13:00.440964

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f4c4d7c12b3a'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('teams',
    sa.Column('_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.PrimaryKeyConstraint('_id')
    )
    op.create_index(op.f('ix_teams__id'), 'teams', ['_id'], unique=False)
    op.create_table('tracks',
    sa.Column('_id', sa.Integer(), nullable=False),
    sa.Column('round', sa.Integer(), nullable=False),
    sa.Column('country', sa.String(length=50), nullable=False),
    sa.Column('city', sa.String(length=50), nullable=False),
    sa.Column('circuit_name', sa.String(length=50), nullable=False),
    sa.Column('gp_name', sa.String(length=50), nullable=False),
    sa.Column('race_date', sa.String(length=50), nullable=False),
    sa.Column('first_gp', sa.Integer(), nullable=False),
    sa.Column('number_of_laps', sa.Integer(), nullable=False),
    sa.Column('circuit_length_km', sa.Float(), nullable=False),
    sa.Column('race_distance_km', sa.Float(), nullable=False),
    sa.Column('lap_record', sa.String(length=50), nullable=False),
    sa.Column('record_owner', sa.String(length=50), nullable=False),
    sa.Column('record_year', sa.Integer(), nullable=False),
    sa.Column('turns', sa.Integer(), nullable=False),
    sa.Column('drs_zones', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('_id'),
    sa.UniqueConstraint('round')
    )
    op.create_index(op.f('ix_tracks__id'), 'tracks', ['_id'], unique=False)
    op.create_table('drivers',
    sa.Column('_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('abbreviation', sa.String(length=50), nullable=False),
    sa.Column('number', sa.String(length=50), nullable=False),
    sa.Column('country', sa.String(length=50), nullable=False),
    sa.Column('podiums', sa.String(length=50), nullable=False),
    sa.Column('points', sa.Integer(), nullable=False),
    sa.Column('grands_prix_entered', sa.String(length=50), nullable=True),
    sa.Column('world_championships', sa.String(length=50), nullable=True),
    sa.Column('highest_race_finish', sa.String(length=50), nullable=True),
    sa.Column('highest_grid_position', sa.String(length=50), nullable=True),
    sa.Column('date_of_birth', sa.String(length=50), nullable=True),
    sa.Column('place_of_birth', sa.String(length=50), nullable=True),
    sa.Column('_team_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['_team_id'], ['teams._id'], ),
    sa.PrimaryKeyConstraint('_id'),
    sa.UniqueConstraint('abbreviation'),
    sa.UniqueConstraint('name'),
    sa.UniqueConstraint('number')
    )
    op.create_index(op.f('ix_drivers__id'), 'drivers', ['_id'], unique=False)
    op.create_table('raceresults',
    sa.Column('_id', sa.Integer(), nullable=False),
    sa.Column('position', sa.String(), nullable=False),
    sa.Column('no', sa.Integer(), nullable=False),
    sa.Column('starting_grid', sa.Integer(), nullable=False),
    sa.Column('laps', sa.Integer(), nullable=False),
    sa.Column('total_time_gap_retirement', sa.String(length=50), nullable=False),
    sa.Column('points', sa.Integer(), nullable=False),
    sa.Column('fastest_lap', sa.Boolean(), nullable=False),
    sa.Column('_track_id', sa.Integer(), nullable=True),
    sa.Column('_driver_id', sa.Integer(), nullable=True),
    sa.Column('_team_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['_driver_id'], ['drivers._id'], ),
    sa.ForeignKeyConstraint(['_team_id'], ['teams._id'], ),
    sa.ForeignKeyConstraint(['_track_id'], ['tracks._id'], ),
    sa.PrimaryKeyConstraint('_id')
    )
    op.create_index(op.f('ix_raceresults__id'), 'raceresults', ['_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_raceresults__id'), table_name='raceresults')
    op.drop_table('raceresults')
    op.drop_index(op.f('ix_drivers__id'), table_name='drivers')
    op.drop_table('drivers')
    op.drop_index(op.f('ix_tracks__id'), table_name='tracks')
    op.drop_table('tracks')
    op.drop_index(op.f('ix_teams__id'), table_name='teams')
    op.drop_table('teams')
    # ### end Alembic commands ###
